IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  # Nevkládat nový SSH klíč při každém spuštění
  config.ssh.insert_key = false

  # Konfigurace poskytovatele VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Definice virtuálního stroje s názvem "ubuntu"
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
    ubuntu.vm.hostname = "Jez-ubuntu"

    # Přesměrování portu pro SSH
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"
  end

  # Provisioning – zkopírování veřejného SSH klíče
  config.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"

  # Přidání veřejného klíče do authorized_keys
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  # Provisioning – instalace Zabbix agenta (volitelné)
  # config.vm.provision "shell", path: "install-zabbix-agent2.sh"

  # Provisioning – konfigurace Zabbix agenta (volitelné)
  # config.vm.provision "shell", path: "configure-zabbix-agent2.sh"
end
